theme: jekyll-theme-minimal

title: Governing Virtual Worlds
description: Project instructions and team repositories for <a href="https://hls.harvard.edu/academics/curriculum/catalog/default.aspx?o=72386">Governing Virtual Worlds</a> <br><br> Projects <br><br> [Example] <a href="https://docs.google.com/document/d/10GQFbj8mPPwey8RQZxavkvQ0q6px0gAjNe2JFeWNCHg">AI Culture</a>
logo: /3BDA99C5-9050-4DDC-9CAD-87C8EF78AD37.jpeg
