theme: jekyll-theme-minimal

title: Governing Virtual Worlds
description: Project instructions and team repositories for <a href="https://hls.harvard.edu/academics/curriculum/catalog/default.aspx?o=72386">Governing Virtual Worlds</a>
