theme: jekyll-theme-minimal

title: Governing Virtual Worlds
description: Project instructions and team repositories for <a href="https://hls.harvard.edu/academics/curriculum/catalog/default.aspx?o=72386">Governing Virtual Worlds</a> <br><br> Projects will be listed here once complete. <br><br> [Example] <a href="/example.html">AI Culture</a>
